server:
  port: 8901

welcome:
  message: hello there !

app:
  description: Project displays ${welcome.message}

my:
  list: one, two, three

dbvalues:
  params:
    url: http://abcd
    user: foo
    password: bar

config:
    ips:
      - 10.10.10.10
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13
